---
name: Lint

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 0 * * *'

  pull_request:

  push:
    branches:
      - master

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - uses: "actions/setup-python@v1"
        with:
          python-version: "3.x"
      - run: python3 --version

      - run: |
          python3 -m pip install --upgrade pip
          pip3 --version

      - run: |
          pip3 install black
          black --version
          black .

      - run: |
          pip3 install flake8 flake8-docstrings
          flake8 --version
          flake8 .

      - run: |
          pip3 install isort
          isort --version
          isort --check-only

      - run: |
          pip3 install mypy
          mypy --version
          mypy

      - run: |
          pip3 install gitlint
          gitlint --version
          gitlint

      - run: |
          pip3 install yamllint
          yamllint --version
          yamllint -d "{extends: default, rules: {line-length: disable}}" .

      - run: if git ls-files | xargs file | grep CRLF; then exit 1; fi
