---
name: Lint

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 0 * * *'

  pull_request:

  push:
    branches:
      - master

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - uses: "actions/setup-python@v1"
        with:
          python-version: "3.x"
      - run: python3 --version

      - run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements_lint.txt

      - run: black .
      - run: flake8 --count
      - run: isort --check-only
      - run: mypy
      - run: yamllint .
      - run: gitlint

      - run: if git ls-files | xargs file | grep CRLF; then exit 1; fi
