---
name: Push actions

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - uses: "actions/setup-python@v1"
        with:
          python-version: "3.x"
      - run: python3 --version

      - run: |
          python3 -m pip install --upgrade pip
          pip3 --version

      - run: |
          pip3 install black
          black --version
          black .

      - run: |
          pip3 install gitlint
          gitlint --version
          # gitlint should ignore Merge commits by default but it does not seem to do it
          gitlint --ignore body-is-missing -c title-max-length.line-length=50 -c ignore-by-title.regex='^Merge(.*)into(.*)'

      - run: |
          pip3 install yamllint
          yamllint --version
          yamllint -d "{extends: default, rules: {line-length: disable}}" .

      - run: if git ls-files | xargs file | grep CRLF; then exit 1; fi

  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - uses: "actions/setup-python@v1"
        with:
          python-version: "3.x"
      - run: python3 --version

      - run: |
          python3 -m pip install --upgrade pip
          pip3 --version

      - run: |
          pip3 install setuptools wheel
          pip3 show setuptools wheel

      - run: |
          python3 setup.py sdist bdist_wheel
